# questions.toml

[[questions]]
question = "When was the first known use of the word 'quiz'"
answer = "1781"
alternatives = ["1771", "1871", "1881"]

[[questions]]
question = "A technician needs to run a diagnostic DVD on a laptop running Windows 8.1. After setting the boot order in the UEFI BIOS to the internal DVD-RW drive, the laptop still boots into Windows. Which of the following settings needs to be adjusted in order for the laptop to boot from the DVD RW drive?" 
answer = "Secure boot"
alternatives = ["TPM", "Virtualization", "UEFI BIOS password",]

[[questions]]
question = "A technician connects a second monitor to a desktop. It is physically located to the right of the existing monitor, but the mouse pointer can only get to the second monitor by moving to the left edge of the screen of the first monitor. Which of following display settings needs to be adjusted to get the pointer to move with the physical placement of the monitor? "
answer = "Position"
alternatives = ["Scaling", "Rotation", "Resolution",]


